# vim:set ft=dockerfile:

FROM ubuntu:focal as build

SHELL ["/bin/bash", "-xe", "-c"]

COPY . /app/hello-world
WORKDIR /app/hello-world

RUN apt-get update -q \
 && apt-get install -q -y --no-install-recommends \
        python3-pip \
 && python3 -m pip install poetry \
 && poetry export > requirements.txt \
 && poetry build -f wheel

# ----------------------------------------------------------------------------
FROM ubuntu:focal

SHELL ["/bin/bash", "-xe", "-c"]

ARG DEBIAN_FRONTEND=noninteractive

COPY --from=build /app/requirements.txt .
COPY --from=build /app/dist/*.whl .
WORKDIR /app

RUN apt-get update -q \
 && apt-get install -y -q --no-install-recommends \
        python3-wheel \
        python3-pip \
        gunicorn \
 && python3 -m pip install --no-cache-dir --disable-pip-version-check \
        -r requirements.txt \
 && python3 -m pip install  --no-cache-dir --disable-pip-version-check \
        --no-deps *.whl \
 && apt-get remove -y python3-pip python3-wheel \
 && apt-get autoremove -y \
 && apt-get clean -y \
 && rm -f requirements.txt *.whl \
 && rm -rf /var/lib/apt/lists/* \
 && useradd _gunicorn --no-create-home --user-group

USER _gunicorn

CMD ["gunicorn", \
     "--bind", "0.0.0.0:8000", \
     "hello_world:app"]
